// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/encoder.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	Filefullname  string                 `protobuf:"bytes,3,opt,name=filefullname,proto3" json:"filefullname,omitempty"`
	Iteration     int32                  `protobuf:"varint,4,opt,name=iteration,proto3" json:"iteration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_encoder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_encoder_proto_rawDescGZIP(), []int{0}
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *FileRequest) GetFilefullname() string {
	if x != nil {
		return x.Filefullname
	}
	return ""
}

func (x *FileRequest) GetIteration() int32 {
	if x != nil {
		return x.Iteration
	}
	return 0
}

type EncodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodeResponse) Reset() {
	*x = EncodeResponse{}
	mi := &file_proto_encoder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodeResponse) ProtoMessage() {}

func (x *EncodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_encoder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodeResponse.ProtoReflect.Descriptor instead.
func (*EncodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_encoder_proto_rawDescGZIP(), []int{1}
}

func (x *EncodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EncodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_encoder_proto protoreflect.FileDescriptor

const file_proto_encoder_proto_rawDesc = "" +
	"\n" +
	"\x13proto/encoder.proto\x12\aencoder\"\x88\x01\n" +
	"\vFileRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tfile_data\x18\x02 \x01(\fR\bfileData\x12\"\n" +
	"\ffilefullname\x18\x03 \x01(\tR\ffilefullname\x12\x1c\n" +
	"\titeration\x18\x04 \x01(\x05R\titeration\"D\n" +
	"\x0eEncodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2B\n" +
	"\aEncoder\x127\n" +
	"\x06Encode\x12\x14.encoder.FileRequest\x1a\x17.encoder.EncodeResponseB\x16Z\x14test-rpc/proto;protob\x06proto3"

var (
	file_proto_encoder_proto_rawDescOnce sync.Once
	file_proto_encoder_proto_rawDescData []byte
)

func file_proto_encoder_proto_rawDescGZIP() []byte {
	file_proto_encoder_proto_rawDescOnce.Do(func() {
		file_proto_encoder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_encoder_proto_rawDesc), len(file_proto_encoder_proto_rawDesc)))
	})
	return file_proto_encoder_proto_rawDescData
}

var file_proto_encoder_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_encoder_proto_goTypes = []any{
	(*FileRequest)(nil),    // 0: encoder.FileRequest
	(*EncodeResponse)(nil), // 1: encoder.EncodeResponse
}
var file_proto_encoder_proto_depIdxs = []int32{
	0, // 0: encoder.Encoder.Encode:input_type -> encoder.FileRequest
	1, // 1: encoder.Encoder.Encode:output_type -> encoder.EncodeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_encoder_proto_init() }
func file_proto_encoder_proto_init() {
	if File_proto_encoder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_encoder_proto_rawDesc), len(file_proto_encoder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_encoder_proto_goTypes,
		DependencyIndexes: file_proto_encoder_proto_depIdxs,
		MessageInfos:      file_proto_encoder_proto_msgTypes,
	}.Build()
	File_proto_encoder_proto = out.File
	file_proto_encoder_proto_goTypes = nil
	file_proto_encoder_proto_depIdxs = nil
}
